# Generated by Django 3.1 on 2020-08-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20200824_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prio',
            field=models.IntegerField(default=0),
        ),
    ]
